### ISSUE TITLE
Performance Implications

### ISSUE THREAD

**Issue by cawfeecoder** [flokkr/k8s#1]
Is there any performance implications (from a scaling perspective and general hit running at an abstract layer) to running Hadoop on Kubernetes vs Bare Metal?

**Comment by elek** [comment]
It depends from the configuration but I think the generic answer is: no, there isn't. I think it's important to use local volumes instead of any network storage (distributed FS on top of a network FS is not a good idea). 

When the real storage is a simple directory (and not overlayfs or any other tricky fs) conainers are nothing more just some additional cgroup / namespace separation. Shouldn't have any significant performance problems.
